name: tes
channels:
  - defaults
dependencies:
  - python=3.8.18
  - numpy=1.23.5
  - scipy=1.10.1
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - ipython=8.12.2
  - notebook=7.0.6
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - cupy=8.3.0
  - tqdm=4.65.0
  - ipympl=0.9.3
  - pip=23.3.1
  - pip:
      - mplcursors==0.5.3
      - pyperclip==1.8.2
